# Generated by Django 3.2 on 2023-03-01 07:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='project_image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=core.models.upload_to, verbose_name='Image'),
        ),
    ]
