# Generated by Django 3.2 on 2023-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='live_demo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
